
version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    volumes:
      - ./db:/data/db
      - ./log:/var/log/mongodb
    ports:
      - 27017:27017
