version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 83:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./log:/var/log/nginx
      - ./www:/usr/share/nginx/html

